Apply suggestion from @PrivatePuffin
Signed-off-by: Kjeld Schouten <info@kjeldschouten.nl>

diff --git a/charts/stable/kometa/values.yaml b/charts/stable/kometa/values.yaml
--- a/charts/stable/kometa/values.yaml
+++ b/charts/stable/kometa/values.yaml
@@ -37,7 +37,7 @@ workload:
                 echo "Config file exists! Skipping..."
               else
                 echo "Config file is missing, getting a new one!"
-                curl -fLvo /app/config/config.yml https://raw.githubusercontent.com/kometa-team/kometa/master/config/config.yml.template || (echo "Downloading config file, FAILED..." && exit 1)
+                curl -fLvo /config/config.yml https://raw.githubusercontent.com/kometa-team/kometa/master/config/config.yml.template || (echo "Downloading config file, FAILED..." && exit 1)
               fi
       containers:
         main:
