Change path config folder
Signed-off-by: Boemeltrein <130394941+Boemeltrein@users.noreply.github.com>

diff --git a/charts/stable/kometa/values.yaml b/charts/stable/kometa/values.yaml
--- a/charts/stable/kometa/values.yaml
+++ b/charts/stable/kometa/values.yaml
@@ -32,14 +32,16 @@ workload:
           args:
             - |
               echo "Creating config.yml file..."
-              if [ -f /config/config.yml ]; then
+              if [ -f /app/config/config.yml ]; then
                 echo "Config file exists! Skipping..."
               else
                 echo "Config file is missing, getting a new one!"
-                curl -fLvo /config/config.yml https://raw.githubusercontent.com/kometa-team/kometa/master/config/config.yml.template || (echo "Downloading config file, FAILED..." && exit 1)
+                curl -fLvo /app/config/config.yml https://raw.githubusercontent.com/kometa-team/kometa/master/config/config.yml.template || (echo "Downloading config file, FAILED..." && exit 1)
               fi
       containers:
         main:
+          env:
+            KOMETA_CONFIG: /app/config/config.yml
           probes:
             liveness:
               enabled: false
@@ -54,5 +56,5 @@ workload:
 persistence:
   config:
     enabled: true
-    mountPath: /config
+    mountPath: /app/config
     targetSelectAll: true
